#!/usr/bin/env python3
"""Tag Soup — Generate all 101 recipe post pages"""

import os, json, random
from pathlib import Path

BLOG_DIR = Path("/home/kodaagentmt/tag-soup-blog-clone")
POSTS_DIR = BLOG_DIR / "posts"
POSTS_DIR.mkdir(exist_ok=True)

BASE_IMAGES = [
    "elk-bolognese.jpg",
    "campfire-chili.jpg",
    "bison-steak.jpg",
    "venison-stew.jpg",
    "duck-confit.jpg",
    "smoked-jerky.jpg",
]

RECIPES = [
    # ELK
    ("Elk", "Elk Sloppy Joes with Pickled Jalapenos", "Ground elk shoulder with pickled jalapenos, melted cheese on a toasted bun. Fast, filling, and ready in 20 minutes.", "1 lb ground elk, 4 hoagie buns, 1 cup pickled jalapenos, 4 slices American cheese, 1/2 cup BBQ sauce, 1 tbsp butter", "Brown elk in a hot cast iron skillet, add BBQ sauce and jalapenos, simmer 5 minutes. Toast buns with butter, pile elk mixture on top, lay on cheese, serve immediately.", "Elk is lean — don't overcook or it'll dry out. The cheese melts faster if you cover the pan."),
    ("Elk", "Elk Tamales with Red Chile Sauce", "Elk braised in red chile sauce wrapped in corn masa. Old-school and worth the effort.", "1 lb ground elk, 2 cups red chile powder, 2 cups masa harina, 1 tbsp lard or butter, 1 onion, chicken broth, cumin, salt", "Brown elk with onion, stir in red chile and broth, simmer 30 min. Make masa with hot water and fat, spread on corn husks, fill with elk, roll and steam 45 minutes.", "Soak corn husks overnight before using. The elk filling can be made a day ahead."),
    ("Elk", "Elk Shawarma Plate", "Spiced elk shoulder seared hard, served over rice with tahini, cucumber, and pita.", "1 lb elk shoulder, 2 tbsp shawarma spice, 1 cup rice, tahini, cucumber, tomato, pita bread, lemon", "Slice elk thin, coat with shawarma spice, sear in smoking hot cast iron 2 min per side. Rest 5 minutes. Serve over rice with tahini sauce, diced cucumber, tomato, and warm pita.", "Shawarma spice is usually cumin, coriander, turmeric, paprika, garlic powder. Make your own or buy pre-mixed."),
    ("Elk", "Elk Green Chile Stew", "Tender elk shoulder with roasted green chiles, onion, and garlic. One pot, deeply satisfying.", "1.5 lbs elk shoulder, 4 roasted green chiles, 1 onion, 3 cloves garlic, 2 cups beef broth, cumin, salt, pepper, lime", "Cut elk into 1-inch chunks, brown in Dutch oven. Add diced onion and garlic, cook 5 min. Add chiles, broth, cumin, bring to boil, reduce to low, cover and simmer 2 hours. Season and squeeze lime over it.", "Elk shoulder is best for this — the long braise breaks down the tissue. Use canned green chiles in a pinch."),
    ("Elk", "Elk Backstrap with Wild Mushroom Cream Sauce", "Elk backstrap seared to medium-rare, topped with a quick cream sauce and mushrooms.", "1 elk backstrap, 8 oz mixed mushrooms, 1 cup heavy cream, 2 shallots, thyme, butter, olive oil, salt, pepper", "Salt and pepper the backstrap. Sear in a screaming hot cast iron 3 min per side. Rest on a cutting board. In the same pan, melt butter, sauté mushrooms and shallots 5 min. Add cream and thyme, reduce by half. Slice elk thin, spoon sauce over top.", "Pull the elk at medium-rare and let it rest — it keeps cooking. Don't skip the rest time."),
    ("Elk", "Elk Chili Colorado", "Dried New Mexico chiles make a deep red sauce that transforms elk shoulder into something incredible.", "1.5 lbs elk shoulder, 4 dried New Mexico chiles, 1 can diced tomatoes, 1 onion, 3 cloves garlic, beef broth, cumin, salt", "Toast chiles in dry pan 30 seconds, soak in hot water 20 min. Blend rehydrated chiles with some soaking liquid. Brown elk chunks, set aside. Sauté onion and garlic, add chile sauce, tomatoes, broth, return elk. Simmer covered 2.5 hours.", "New Mexico chiles are mild with a deep red color. They give the chili its signature flavor and color."),
    ("Elk", "Elk Meatballs in Tomato Basil Sauce", "Tender elk meatballs simmered in a simple tomato basil sauce. Lighter than beef, just as satisfying.", "1 lb ground elk, 1/4 cup breadcrumbs, 1 egg, 1/4 cup parmesan, 1 can crushed tomatoes, fresh basil, garlic, olive oil, salt, pepper", "Mix elk with breadcrumbs, egg, parmesan, salt and pepper. Form into 12 balls. Brown in olive oil in a deep skillet, set aside. Add garlic to pan, cook 1 min, add tomatoes and basil, simmer 15 min. Return meatballs to sauce, cover and simmer 20 more minutes.", "Don't overmix the elk — mix just until combined or the meatballs will be tough."),
    ("Elk", "Elk Rueben Sandwich", "Thin-sliced elk roast on rye with caramelized sauerkraut, Swiss cheese, and Russian dressing.", "1 lb elk deli slices or thin-sliced roast, 2 cups sauerkraut, 4 slices rye bread, 4 slices Swiss cheese, Russian dressing, butter", "Caramelize sauerkraut in a buttered pan 5 minutes. Toast rye with butter until golden. Layer elk, sauerkraut, cheese, and dressing on one slice, top with another, press on the griddle until cheese melts.", "If using a whole roast instead of deli slices, sear it hard then roast at 325°F until medium-rare internally."),
    ("Elk", "Elk Tacos with Roasted Salsa Verde", "Seasoned elk in warm corn tortillas with a bright tomatillo salsa verde.", "1 lb ground elk, corn tortillas, 1 lb tomatillos, 2 jalapenos, 1/2 onion, garlic, cilantro, cumin, lime, salt", "Brown elk with cumin and salt, set aside. Char tomatillos, jalapenos, and onion under the broiler 5 minutes. Blend with garlic, cilantro, and lime. Warm tortillas, fill with elk and top with salsa verde.", "Tomatillos can be swapped for green salsa from a jar — just doctor it with fresh lime and cilantro."),
    ("Elk", "Smoked Elk Summer Sausage", "Coarsely ground elk with pork fat and seasoning, stuffed into casings and slow-smoked.", "2 lbs elk, 1/2 lb pork fat, 2 tbsp mustard seed, 1 tbsp coriander, 1 tbsp black pepper, 1 tsp garlic powder, 1 tsp Prague powder #1, salt", "Grind elk and pork fat together through a coarse plate. Mix in seasonings and Prague powder. Stuff into hog casings. Smoke at 160°F for 4 hours, then 180°F until internal hits 155°F. Slice thin and serve.", "This one needs a smoker. If you don't have one, you can use a grill with wood chips in a foil packet."),
    # VENISON
    ("Venison", "Venison Stew with Root Vegetables", "Classic venison stew with carrots, parsnips, and potatoes. Low and slow is the key.", "2 lbs venison shoulder, 3 carrots, 3 parsnips, 4 potatoes, 1 onion, 4 cups beef broth, thyme, bay leaf, flour, salt, pepper", "Cut venison into 2-inch chunks, toss in flour, brown in batches in a Dutch oven. Set aside. Sauté onion, add broth, return meat, add thyme and bay leaf. Bring to boil, reduce to low, cover and cook 1.5 hours. Add root vegetables, cook 45 more minutes.", "Venison benefits from long cooking to break down the connective tissue. Don't rush it."),
    ("Venison", "Smoked Venison Jerky — Teriyaki Style", "Thin-sliced venison marinated in teriyaki, smoked low and slow until leathery.", "2 lbs venison, 1/2 cup soy sauce, 2 tbsp worcestershire, 2 tbsp brown sugar, 1 tbsp garlic powder, 1 tbsp smoked paprika, 1 tsp black pepper", "Slice venison 1/4 inch thick against the grain. Mix marinade, combine with meat, marinate 12-24 hours in the fridge. Smoke at 130°F for 4-5 hours until dry and leathery but still flexible.", "A food dehydrator works if you don't have a smoker. The key is getting the meat truly dry."),
    ("Venison", "Venison Stir-Fry with Snap Peas and Ginger", "Venison loin sliced thin, seared fast with snap peas, ginger, and soy sauce.", "1 lb venison loin, 2 cups snap peas, 2 tbsp ginger, 3 cloves garlic, 3 tbsp soy sauce, 1 tbsp sesame oil, rice", "Slice venison thin against the grain. Heat a cast iron or wok as hot as possible. Add oil, sear venison 1 minute per side, remove. Add snap peas, ginger, garlic — cook 2 minutes. Return venison, add soy sauce and sesame oil, toss and serve over rice.", "Get the pan truly ripping hot. A cold pan = grey, tough meat. Do this fast."),
    ("Venison", "Venison Tacos with Pineapple Salsa", "Seasoned venison in corn tortillas with fresh pineapple salsa and cilantro.", "1 lb ground venison, cumin, chili powder, salt, corn tortillas, 1 cup fresh pineapple, 1/4 cup red onion, cilantro, lime, jalapeno", "Brown venison with cumin, chili powder, and salt. For salsa: dice pineapple, mix with minced red onion, cilantro, lime, and jalapeno. Warm tortillas, fill with venison, top with pineapple salsa.", "The salsa can be made an hour ahead — the lime tenderizes the pineapple and develops flavor."),
    ("Venison", "Slow-Cooker Venison Roast", "Set it in the morning, come back to fall-apart tender venison roast.", "3 lb venison roast, 1 packet onion soup mix, 1 can cream of mushroom soup, 1 cup beef broth, 4 cloves garlic, 2 onions, butter", "Season roast with salt and pepper, sear in a hot Dutch oven. Place in slow cooker with sliced onions, garlic, soup mix, soup, and broth. Cook on low 8 hours. Serve over mashed potatoes.", "The secret is low and slow. Venison goes from tough to tender in about 8 hours at low heat."),
    ("Venison", "Venison Salisbury Steak", "Ground venison patties in rich onion gravy. Old-school comfort food.", "1.5 lbs ground venison, 1 egg, 1/4 cup breadcrumbs, 1 onion, 2 cups beef broth, 2 tbsp flour, thyme, salt, pepper", "Mix venison with egg, breadcrumbs, salt, pepper — form 6 patties. Brown in cast iron, set aside. Slice and sauté onion in the same pan. Add flour, stir 2 minutes, add broth and thyme, bring to simmer. Return patties, cover and cook 20 minutes.", "The gravy is built in the same pan — don't wash it between steps."),
    ("Venison", "Venison Italian Sub", "Thin-sliced venison with provolone, pepperoncinis, and giardiniera on a hoagie.", "1 lb thinly sliced venison roast, 4 hoagie buns, 8 slices provolone, 1/2 cup pepperoncinis, 1/2 cup giardiniera, olive oil, red wine vinegar, oregano", "Toast hoagie buns. Layer provolone and venison on the bun, top with pepperoncinis and giardiniera. Drizzle with olive oil and red wine vinegar, sprinkle with oregano. Toast on a griddle until cheese melts.", "A deli-sliced venison roast works best for this. Roast a venison shoulder at 325°F until medium-rare, then slice thin."),
    ("Venison", "Venison Potato Soup", "Thick, velvety potato soup loaded with shredded venison jerky for a protein punch.", "1 lb shredded smoked venison jerky, 4 large russets, 1 onion, 3 cups chicken broth, 1 cup cream, butter, chives, salt, pepper", "Dice potatoes and onion, cook in broth until very tender, about 20 minutes. Add cream and butter, mash some potatoes to thicken. Stir in shredded jerky, season, and serve topped with chives.", "The jerky adds a deep smoky flavor — even better if you make your own."),
    ("Venison", "Venison Curry with Sweet Potato", "Venison and sweet potato in a warming coconut curry. Bold flavors, one pot.", "1 lb ground venison, 1 large sweet potato, 1 can coconut milk, 2 tbsp curry powder, 1 onion, garlic, ginger, 1 cup rice, cilantro", "Brown venison, set aside. Sauté onion and garlic, add curry powder and toast 1 minute. Add cubed sweet potato, coconut milk, bring to simmer, cook 15 minutes until potato is tender. Return venison, serve over rice with cilantro.", "Any curry powder works — add more for extra heat. A spoon of mango chutney sweetens it nicely."),
    ("Venison", "Venison Mushroom Stroganoff", "Egg noodles and sautéed venison in a rich sour cream and mushroom sauce.", "1 lb venison loin, 8 oz mushrooms, 1 cup sour cream, 1 cup egg noodles, 1 onion, 2 cloves garlic, beef broth, butter, flour, salt, pepper, paprika", "Slice venison thin, salt and pepper. Brown quickly in butter, set aside. Sauté mushrooms and onion, add garlic, sprinkle with flour and paprika, stir 2 minutes. Add broth, simmer, return meat, stir in sour cream off heat. Serve over egg noodles.", "Never boil sour cream — it will curdle. Add it off the heat and stir gently."),
    ("Venison", "Venison Neck Ragu with Rigatoni", "Venison neck braised until it falls apart, served over thick rigatoni with parmesan.", "2 lbs venison neck, 1 can crushed tomatoes, 1 onion, 4 cloves garlic, 1 cup red wine, 1 lb rigatoni, parmesan, thyme, rosemary, salt, pepper", "Season and brown neck pieces in Dutch oven. Add onion, garlic, cook 5 min. Add wine, reduce by half. Add tomatoes and herbs, cover and braise at 300°F for 3 hours until meat falls off bone. Shred meat, serve over rigatoni with parmesan.", "Neck is an underrated cut — cheap and incredible when braised low and slow."),
    ("Venison", "Venison Fried Pickles with Sriracha Aioli", "Crispy fried venison backstrap slices with a spicy sriracha dipping sauce.", "1 lb venison backstrap, 1 cup dill pickle chips, 1 cup flour, 1 egg, 1/2 cup milk, 1 cup panko, 1/2 cup sriracha, 1/2 cup mayo, salt, oil for frying", "Slice backstrap 1/2 inch thick, salt. Make a breading station: flour, egg+milk wash, panko. Dip each slice in order. Fry at 375°F in batches 2-3 minutes until golden. Mix sriracha and mayo for dipping sauce.", "Venison backstrap is premium — this recipe makes it count. The pickles add a tangy crunch."),
    ("Venison", "Venison Liver and Onions", "Thinly sliced venison liver with caramelized onions and bacon. A camp classic.", "1 lb venison liver, 4 strips bacon, 2 large onions, flour, butter, salt, pepper, capers", "Slice liver thin, dust with flour. Fry bacon until crisp, set aside. Cook onions in bacon fat slowly 15 minutes until golden. Brown liver in the same pan 1-2 minutes per side. Arrange liver, top with onions and bacon, garnish with capers.", "Don't overcook the liver — 1-2 minutes per side max. It goes from perfect to grainy fast."),
    ("Venison", "Venison Pastrami on Rye", "Cured and spiced venison roast, sliced thin on rye with Swiss and Russian dressing.", "2 lb venison roast, 2 tbsp coriander, 1 tbsp black pepper, 1 tbsp garlic powder, 1 tbsp mustard seeds, 1/4 cup brown sugar, 1/4 cup Prague powder #1, rye bread, Swiss, Russian dressing, sauerkraut", "Cure roast with Prague powder and brown sugar 5 days. Rinse, coat with spices. Sear hard, then roast at 325°F to medium-rare. Slice thin. Stack on rye with Swiss, Russian dressing, and sauerkraut.", "This is a multi-day cure — plan ahead. But the result is incredible pastrami."),
    ("Venison", "Venison Chorizo Breakfast Tacos", "Spiced venison chorizo with eggs, potatoes, and salsa verde in warm corn tortillas.", "1 lb ground venison, 2 tbsp chorizo spice (cumin, paprika, garlic, oregano, chili powder), 4 eggs, 2 cups frozen hash browns, corn tortillas, salsa verde, cilantro", "Brown venison with chorizo spice, set aside. Cook hash browns in chorizo fat until crispy. Scramble eggs in the same pan. Warm tortillas, fill with chorizo, eggs, potatoes, salsa verde, and cilantro.", "Make your own chorizo spice — it's cheaper than buying pre-mixed."),
    ("Venison", "Venison Bibimbap", "Korean-style rice bowl with seasoned venison, vegetables, and a fried egg.", "1 lb ground venison, 3 cups short-grain rice, 2 cups spinach, 1 cup bean sprouts, 1 zucchini, 2 carrots, 4 eggs, gochujang, sesame oil, soy sauce, garlic", "Cook rice. Sauté vegetables separately with garlic and sesame oil. Brown venison with soy sauce. Arrange rice in bowls, top with vegetables and meat, fry eggs sunny-side up. Serve with gochujang.", "The key is getting each component cooked separately so flavors stay clean."),
    # BISON
    ("Bison", "Bison Steak Frites with Herb Butter", "Thick-cut bison sirloin seared hard with compound herb butter melting over the top.", "2 bison sirloin steaks, 4 tbsp butter, 2 tbsp fresh thyme, 2 tbsp fresh rosemary, 1 shallot, salt, pepper, vegetable oil", "Make herb butter: mix softened butter with minced thyme, rosemary, and shallot. Roll in parchment. Salt and pepper steaks. Sear in screaming hot cast iron 2-3 min per side. Top with herb butter and rest 5 minutes.", "Bison is leaner than beef — pull it at medium-rare, not medium. The herb butter makes up for the leanness."),
    ("Bison", "Bison Bourguignon", "Bison shoulder braised in red wine with mushrooms, pearl onions, and bacon. A French classic.", "2 lbs bison shoulder, 1 bottle red wine, 8 oz mushrooms, 1 cup pearl onions, 4 strips bacon, 2 carrots, beef broth, tomato paste, thyme, bay leaf, flour", "Cut bison into 2-inch chunks, salt and flour. Brown in batches. Cook bacon, set aside. Brown onions and carrots. Add wine, broth, tomato paste, thyme, bay leaf. Return bison and bacon. Braise at 325°F for 3 hours.", "Use a sturdy red wine — the longer it cooks, the better it gets. Plan for a 3+ hour cook."),
    ("Bison", "Bison Burgers with Caramelized Onions and Gruyère", "Juicy bison burgers topped with slow-cooked onions and melted Gruyère.", "1.5 lbs ground bison, 2 large onions, 4 slices Gruyère, 4 brioche buns, butter, salt, pepper", "Slice onions thin, cook slowly in butter 25 minutes until deep golden. Season bison with salt and pepper, form 4 patties. Cook in cast iron 3-4 min per side for medium. Add cheese, cover to melt. Toast buns, assemble.", "Keep bison burgers medium-rare to medium — any more and they dry out."),
    ("Bison", "Bison French Dip Sandwiches", "Slow-roasted bison with melted provolone and a rich au jus for dipping.", "2 lb bison chuck roast, 1 can beef broth, 1 onion, 4 hoagie buns, 8 slices provolone, garlic, salt, pepper", "Season and sear roast. Place in Dutch oven with sliced onion and broth. Braise at 325°F for 3 hours until fork-tender. Slice thin, pile on hoagies with provolone, cover and steam 2 min. Serve with au jus.", "The au jus is built in the same pot — don't waste a drop."),
    ("Bison", "Bison Beefaroni", "Cylindrical pasta in a rich bison and tomato meat sauce. Crowd-pleaser comfort food.", "1 lb ground bison, 1 lb penne pasta, 1 can crushed tomatoes, 1 onion, 4 cloves garlic, 1 tsp each: basil, oregano, sugar, salt, parmesan, red pepper flakes", "Brown bison, set aside. Sauté onion and garlic, add tomatoes and spices, simmer 20 min. Cook penne, reserve pasta water. Combine sauce and pasta, add pasta water to loosen. Finish with parmesan.", "Bison replaces beef in the classic — same comfort, less fat."),
    ("Bison", "Smoked Bison Brisket", "Brined bison brisket smoked low and slow until it melts.", "5 lb bison brisket, 1/4 cup coarse salt, 1/4 cup brown sugar, 2 tbsp black pepper, 1 tbsp garlic powder, mustard binder, BBQ sauce", "Brine brisket 12-24 hours. Rinse, pat dry, coat with mustard, apply rub. Smoke at 225°F until internal hits 165°F (usually 6-8 hours). Wrap in butcher paper, continue to 205°F. Rest 1 hour, slice against the grain.", "Bison brisket is leaner than beef — don't skip the brine or it'll dry out."),
    ("Bison", "Bison Osso Buco", "Bison shanks braised in red wine with tomatoes and aromatics until the bone marrow melts.", "4 bison shanks, 1 bottle red wine, 1 can diced tomatoes, 2 carrots, 2 celery stalks, 1 onion, 4 cloves garlic, thyme, rosemary, bay leaf, flour", "Season and flour shanks, brown in Dutch oven. Add diced vegetables and garlic, cook 5 min. Add wine and tomatoes, herbs, bring to simmer. Cover and braise at 325°F for 3 hours until meat falls from bone.", "Serve with gremolata: mix lemon zest, garlic, and parsley. It cuts through the richness."),
    ("Bison", "Bison Enchiladas with Roasted Poblano Sauce", "Rolled tortillas filled with bison and cheese, covered in smoky poblano sauce.", "1 lb ground bison, 12 corn tortillas, 4 poblano peppers, 2 cups shredded cheese, 1 onion, garlic, cumin, sour cream, chicken broth", "Char poblanos, peel and blend with garlic, cumin, broth and a touch of sour cream. Brown bison with onion and garlic. Warm tortillas, fill with bison and cheese, roll and place in baking dish. Cover with poblano sauce and more cheese. Bake 375°F for 20 min.", "Poblanos range from mild to moderately hot — taste yours and adjust."),
    ("Bison", "Smoked Bison Baby Back Ribs", "Bison ribs slow-smoked until the meat pulls away from the bone.", "2 racks bison ribs, 1/4 cup brown sugar, 2 tbsp paprika, 1 tbsp each: garlic powder, onion powder, cayenne, black pepper, salt, BBQ sauce", "Remove membrane from back of ribs. Combine rub, apply generously. Smoke at 225°F for 5 hours. Wrap in foil with a splash of apple juice, cook 2 more hours. Unwrap, apply BBQ sauce, cook 30 more minutes.", "They're done when you can pull a bone end and meat comes with it easily."),
    ("Bison", "Bison Tagliatelle with Brown Butter and Sage", "Fresh egg noodles with bison medallions in a nutty brown butter sauce.", "1 lb bison tenderloin, 12 oz fresh tagliatelle, 6 tbsp butter, 12 fresh sage leaves, 1/4 cup hazelnuts, parmesan, lemon, salt, pepper", "Cut bison into 1-inch medallions, salt and pepper. Brown in butter in a hot pan 2 min per side. Remove, add more butter, cook sage until crispy, add hazelnuts. Cook pasta al dente, toss with brown butter, top with bison and sage.", "Brown butter is the key — watch it closely, it goes from golden to burned fast."),
    # WILD BOAR
    ("Wild Boar", "Cast Iron Wild Boar Ribs", "Wild boar ribs grilled low and slow with a sweet and smoky dry rub.", "2 racks wild boar ribs, 1/4 cup brown sugar, 2 tbsp paprika, 1 tbsp garlic powder, 1 tbsp black pepper, 1 tsp cayenne, salt, BBQ sauce", "Remove membrane, coat with dry rub. Grill at 300°F or smoke for 3 hours. Wrap in foil with splash of broth, cook 2 more hours. Unwrap, brush with BBQ sauce, cook 1 more hour until tender.", "Wild boar is gamier than pork — the longer cook softens the gamey flavor."),
    ("Wild Boar", "Wild Boar Ragu with Pappardelle", "Slow-braised wild boar shoulder in a rich tomato wine sauce over wide noodles.", "2 lb wild boar shoulder, 1 can crushed tomatoes, 1 cup red wine, 1 onion, 4 cloves garlic, 1 carrot, 1 celery, rosemary, thyme, 12 oz pappardelle pasta, parmesan", "Cut boar into chunks, brown in Dutch oven. Add diced onion, carrot, celery, garlic — cook 10 min. Add wine, reduce by half. Add tomatoes and herbs, cover and braise at 325°F for 3 hours. Shred meat, serve over pappardelle with parmesan.", "Wild boar has more fat than deer — this makes it forgiving and juicy."),
    ("Wild Boar", "Wild Boar Chorizo and Eggs", "Spicy wild boar chorizo scrambled with eggs and served with warm tortillas.", "1 lb ground wild boar, 2 tbsp chorizo spice (cumin, paprika, oregano, garlic, chili powder), 4 eggs, 1/4 cup salsa verde, corn tortillas, cilantro", "Brown boar with chorizo spice. Scramble eggs in the same pan. Warm tortillas, serve chorizo and eggs with salsa verde and cilantro.", "Homemade chorizo spice is better than anything from a packet."),
    ("Wild Boar", "Boar Smoked Sausage with Peppers and Onions", "Smoked wild boar sausage sliced and charred with sweet peppers and onions.", "1 lb smoked wild boar sausage, 2 bell peppers, 2 onions, 2 tbsp olive oil, 1 tsp smoked paprika, salt, pepper", "Slice sausage 1/2 inch thick, char in a hot cast iron. Set aside. Cook peppers and onions in the same pan until soft and slightly charred. Return sausage, season with paprika, salt, and pepper. Serve on its own or in a hoagie.", "The slightly gamey flavor of boar sausage is mellowed by the sweet peppers."),
    ("Wild Boar", "Wild Boar Pozole Rojo", "Wild boar shoulder in a rich red chile pozole broth with hominy.", "2 lb wild boar shoulder, 1 can white hominy, 3 dried guajillo chiles, 2 chipotles in adobo, 1 onion, 4 cloves garlic, cumin, oregano, chicken broth, toppings: radish, cabbage, lime, cilantro", "Toast and soak guajillo chiles. Brown boar shoulder. Sauté onion and garlic, add blended chiles and chipotles, cook 2 min. Add boar, broth, cumin, oregano. Braise 2.5 hours. Shred meat, add hominy, cook 30 more minutes.", "Pozole is even better the next day when the flavors deepen."),
    ("Wild Boar", "Wild Boar Bacon Smash Burger", "Smashed wild boar patties with crispy bacon, caramelized onions, and melted cheddar.", "1 lb ground wild boar, 4 strips bacon, 1 large onion, 4 brioche buns, 4 slices cheddar, salt, pepper, butter", "Cook bacon until crisp, set aside. Slice onion thin, cook in bacon fat until deep golden. Form boar into 4 loose balls. Smash hard in a hot cast iron, season, cook 2 min, flip, add cheese and cover. Toast buns, assemble with bacon, onions.", "Smashing creates a crispy, lacey edge that's hard to beat."),
    ("Wild Boar", "Wild Boar Osso Buco with Gremolata", "Braised wild boar shanks with gremolata over creamy polenta.", "4 wild boar shanks, 1 bottle red wine, 1 can crushed tomatoes, 1 onion, 4 cloves garlic, 2 carrots, 2 celery, thyme, rosemary, bay leaf, lemon zest, parsley, garlic", "Season and flour shanks, brown in Dutch oven. Add vegetables, garlic, wine, tomatoes, herbs. Braise at 325°F for 3 hours. Make gremolata: mix lemon zest, minced garlic, parsley. Serve shanks over polenta with gremolata.", "Wild boar shanks are meaty and gamey — the long braise tames both."),
    ("Wild Boar", "Wild Boar Curry with Coconut Milk", "Wild boar shoulder in a rich coconut curry with vegetables and rice.", "1.5 lb wild boar shoulder, 1 can coconut milk, 3 tbsp curry powder, 1 onion, 3 cloves garlic, 1 bell pepper, 1 cup frozen peas, rice, cilantro", "Cut boar into chunks, brown in batches. Sauté onion and garlic, add curry powder, toast 1 min. Return boar, add coconut milk, bring to simmer, cook 1.5 hours. Add pepper and peas, cook 15 more min. Serve over rice with cilantro.", "Wild boar holds up beautifully to long braising — it gets tender without falling apart."),
    ("Wild Boar", "Wild Boar Rinds Cracklings", "Crispy wild boar skin fried until bubbled and golden. Addictively crunchy.", "2 lbs wild boar belly skin, coarse salt, black pepper, garlic powder, vegetable oil", "Score the skin, coat with salt and pepper. Lay skin-side down in a cold pan, add oil. Bring to medium heat, press with a spatula. Cook 15-20 minutes until bubbled and golden. Drain on paper towels, season with garlic powder.", "Pat the skin completely dry before cooking or it won't bubble properly."),
    # WATERFOWL
    ("Wildfowl", "Duck Confit Tacos with Pickled Onions", "Slow-cooked duck leg confit shredded into tacos with quick-pickled red onions.", "4 duck legs, 1 cup duck fat (or lard), 1 tbsp salt, 1 tsp thyme, 6 corn tortillas, 1/2 cup quick-pickled onions, cilantro, lime, salsa verde", "Season duck legs with salt and thyme, refrigerate overnight. Cover with fat in a Dutch oven, cook at 300°F for 3 hours until tender. Shred meat, crisp skin-side down in a hot pan. Serve in tortillas with pickled onions and cilantro.", "Duck confit keeps for weeks in the fat — make a big batch."),
    ("Wildfowl", "Smoked Goose Breast with Peach Glaze", "Goose breast smoked rare, sliced thin, with a sweet peach glaze.", "2 goose breasts, 1/4 cup peach preserves, 2 tbsp balsamic vinegar, 1 tbsp butter, salt, pepper, smoke wood: apple or cherry", "Score the skin, season with salt and pepper. Cold-smoke or smoke at 200°F for 1 hour until rare (125°F internal). Rest 10 min. Heat preserves with balsamic and butter, brush on sliced goose.", "Goose is best served rare to medium-rare — the breast is lean and dries out fast."),
    ("Wildfowl", "Duck Fried Rice", "Leftover duck meat fried with rice, scrambled eggs, and vegetables.", "2 cups cooked duck meat (shredded), 4 cups day-old rice, 3 eggs, 1 cup frozen peas and carrots, 3 tbsp soy sauce, 1 tbsp sesame oil, 4 green onions, garlic", "Heat a wok until smoking, add oil, scramble eggs and set aside. Add duck and cook until crispy. Add rice, vegetables, soy sauce, sesame oil — toss until heated through. Return eggs, add green onions.", "Day-old refrigerated rice works best — fresh rice gets mushy."),
    ("Wildfowl", "Goose Gumbo", "Dark, rich goose gumbo with the giblets and leftover goose meat.", "1 goose carcass, 1 lb andouille sausage, 1 cup gumbo file, 1 can diced tomatoes, 3 cups rice, 2 onions, 3 celery stalks, garlic, thyme, bay leaves, chicken broth", "Roast carcass at 400°F for 30 min. Sauté vegetables, add tomatoes and broth, simmer with carcass 2 hours. Strain, return to pot, add sausage and goose meat, thicken with roux or file. Serve over rice.", "Gumbo file thickens and adds authentic flavor — stir in after the boil."),
    ("Wildfowl", "Cast Iron Duck Breast with Cherry Reduction", "Pan-seared duck breast with a quick cherry pan sauce. Elegant and fast.", "2 duck breasts, 1 cup fresh or frozen cherries, 2 tbsp balsamic vinegar, 1 tbsp sugar, 2 sprigs thyme, butter, salt, pepper", "Score duck skin in a crosshatch, salt generously. Sear skin-side down in a cold pan — bring to medium heat, cook 12-15 min until fat renders and skin is crispy. Flip, cook 2 more min. Rest. Add cherries, vinegar, sugar, thyme to pan, reduce by half. Add butter, spoon over sliced duck.", "Serve duck medium-rare — it should be pink throughout."),
    ("Wildfowl", "Smoked Duck Eggs Benedict", "Poached eggs and pulled smoked duck on an English muffin with hollandaise.", "4 eggs, 4 English muffins, 1 lb smoked duck meat, 3 egg yolks, 1/2 cup butter, lemon juice, cayenne, salt", "Make hollandaise: whisk yolks with lemon and cayenne over simmering water, slowly stream in melted butter. Toast English muffins. Warm duck in a pan. Poach eggs 3 minutes. Assemble: muffin, duck, egg, hollandaise.", "Hollandaise is simpler than it seems — keep the heat low and whisk constantly."),
    ("Wildfowl", "Moulard Duck Prosciutto", "Duck breast air-cured for several weeks. Slice thin and serve raw.", "2 Moulard duck breasts, 1/4 cup coarse salt, 2 tbsp sugar, 1 tbsp black pepper, 1 tbsp thyme", "Combine salt, sugar, pepper, thyme. Pack onto duck breasts, refrigerate 5-7 days, flipping daily. Rinse, pat dry, hang in a cool dry place (55°F) for 2-3 weeks. Slice paper-thin.", "This is a project that requires time and the right conditions — cool, dry basement or wine cellar."),
    ("Wildfowl", "Canadian Goose Confit Legs", "Slow-cooked goose legs in duck fat until falling-off-the-bone tender.", "4 Canada goose legs, 2 cups duck fat or lard, 4 cloves garlic, thyme, salt, black pepper", "Season goose legs, cover with duck fat in a Dutch oven. Cook at 325°F for 3 hours until very tender. Remove legs, reduce fat and reserve. Crisp legs skin-side down before serving. Serve with roasted root vegetables.", "Goose legs are tough without long cooking — the confit method transforms them."),
    ("Wildfowl", "Teal Duck Poppers with Bacon", "Spicy teal duck breast wrapped in bacon with a pepper jelly glaze.", "4 teal duck breasts, 8 slices bacon, 4 oz cream cheese, 2 tbsp jalapeno jelly, toothpicks", "Slice duck breasts into 1-inch chunks. Wrap each in half-slice bacon, secure with toothpick. Season. Grill or smoke at 350°F for 20 min, brushing with jalapeno jelly in last 5 min. Serve with extra jelly for dipping.", "Any small duck works — teal are plentiful and the breast is just the right size."),
    ("Wildfowl", "Merganser Gumbo with Duck Andouille", "Merganser duck and homemade andouille sausage in a dark roux gumbo.", "1 merganser duck, 1 lb andouille, 3/4 cup flour, 3/4 cup oil (for roux), 1 large onion, 1 bell pepper, 3 celery stalks, 6 cups duck or chicken stock, 2 tbsp gumbo file, rice", "Make dark roux: heat oil, whisk in flour, cook stirring constantly until dark brown. Add Trinity (onion, pepper, celery), cook 10 min. Add stock, duck and andouille, simmer 2 hours. Stir in file, serve over rice.", "The roux is the heart of the gumbo — don't rush it."),
    ("Wildfowl", "Spoonbill Duck Breast with Plum Sauce", "Spoonbill duck breast seared rare with a quick plum sauce.", "2 spoonbill duck breasts, 1 cup plums, 2 tbsp sugar, 2 tbsp balsamic vinegar, 1 sprig rosemary, butter, salt, pepper", "Score skin, salt and pepper. Sear skin-side down in a cold pan brought to medium heat, 12-15 min until crispy. Flip, cook 1 min. Rest. Add plums, sugar, vinegar, rosemary to pan — cook until plums burst and sauce thickens. Add butter, spoon over sliced duck.", "Spoonbill has a mild flavor — the plum sauce is a natural partner."),
    ("Wildfowl", "Duck Egg Frittata with Morels and Ramps", "Fluffy frittata made with rich duck eggs and foraged mushrooms and ramps.", "6 duck eggs, 4 oz morels (or chanterelles), 4 ramps (or green onions), 1/2 cup cream, 2 tbsp butter, parmesan, salt, pepper", "Sauté morels in butter until golden, add ramps and cook 2 min. Whisk eggs with cream, salt, pepper. Pour over mushrooms in an oven-safe pan. Cook on stovetop 5 min, finish under broiler 3 min. Top with parmesan.", "Duck eggs are richer and bigger than chicken eggs — 6 makes a generous frittata."),
    # SMALL GAME
    ("Small Game", "Southern Fried Rabbit", "Crispy cornmeal-crusted rabbit fried in a cast iron. Down-home cooking.", "1 whole rabbit (cut into pieces), 1 cup buttermilk, 1 cup cornmeal, 1/2 cup flour, 1 tbsp paprika, 1 tsp garlic powder, salt, pepper, lard or vegetable oil for frying", "Soak rabbit pieces in buttermilk 4 hours or overnight. Mix cornmeal, flour, paprika, garlic powder, salt, pepper. Dredge rabbit, fry in 350°F lard in cast iron 12-15 min until golden and cooked through. Rest on a rack.", "Buttermilk tenderizes the rabbit and helps the breading stick."),
    ("Small Game", "Rabbit Cacciatore", "Rabbit braised in a classic Italian hunter-style tomato sauce with peppers and onions.", "1 whole rabbit (cut up), 1 can crushed tomatoes, 1 bell pepper, 1 onion, 4 cloves garlic, 1/2 cup red wine, thyme, rosemary, basil, salt, pepper", "Season and brown rabbit pieces, set aside. Sauté pepper and onion, add garlic, cook 2 min. Add wine, reduce slightly. Add tomatoes and herbs, return rabbit. Cover and simmer 1 hour until tender.", "Rabbit is lean — don't let it boil dry, add a splash of broth if needed."),
    ("Small Game", "Smoked Rabbit with Apricot Mustard Glaze", "Whole rabbit smoked low and slow with a sweet-tangy glaze.", "1 whole rabbit, 3 tbsp apricot preserves, 2 tbsp whole-grain mustard, 1 tbsp apple cider vinegar, salt, pepper", "Brine rabbit 4 hours. Smoke at 225°F for 2.5 hours. Mix glaze ingredients, brush on rabbit in last 30 min. Continue until internal temp hits 160°F.", "The glaze caramelizes beautifully — watch it doesn't burn."),
    ("Small Game", "Rabbit and Dumplings", "Tender rabbit in a thick, herby stew with fluffy dropped dumplings.", "1 whole rabbit (cut up), 3 cups rabbit or chicken broth, 1 onion, 3 celery stalks, 2 carrots, thyme, bay leaf, 1 cup flour, 1/2 cup cold butter (for dumplings), 1/4 cup milk, parsley", "Braise rabbit in broth with vegetables until tender, about 1 hour. Remove meat. Make dumpling dough: mix flour, cold butter, milk, parsley — drop by spoonfuls into simmering broth. Cook 15 min covered. Return rabbit meat, serve.", "Don't lift the lid while dumplings cook — steam is essential."),
    ("Small Game", "Rabbit Tikka Masala", "Rabbit pieces in a rich, creamy tomato and yogurt masala sauce.", "1 whole rabbit (cut up), 1 cup yogurt, 3 tbsp garam masala, 1 can crushed tomatoes, 1 cup heavy cream, 1 onion, 4 cloves garlic, ginger, cumin, rice, cilantro", "Marinate rabbit in yogurt, garam masala, and lemon 4 hours. Brown rabbit pieces, set aside. Sauté onion, garlic, ginger, cumin — add tomatoes, cream, and remaining spices. Return rabbit, simmer 45 min. Serve over basmati rice.", "Rabbit takes the marinade beautifully — the yogurt tenderizes the lean meat."),
    ("Small Game", "Pheasant Pot Pie", "Creamy pheasant and vegetable pie with a flaky crust. The ultimate comfort food.", "2 pheasant breasts, 1 cup each: peas, carrots, diced potatoes, 1 onion, 2 cups chicken broth, 1/2 cup heavy cream, 1 pie crust (top), butter, flour, salt, pepper", "Poach pheasant breasts in broth 15 min, shred meat. Sauté vegetables, add flour, cook 2 min. Add broth and cream, simmer until thick. Add pheasant, pour into baking dish, top with pie crust, bake 400°F for 25 min until golden.", "Use leftover pheasant or chicken — this recipe works with both."),
    ("Small Game", "Smoked Pheasant Breast with Gouda", "Smoked pheasant breast sliced thin over smoked Gouda and crackers.", "4 pheasant breasts, 4 oz smoked Gouda, 1 tbsp olive oil, salt, pepper, apple wood chips", "Cold-smoke or grill-smoke pheasant at 200°F for 1 hour. Let rest 10 min. Slice thin, fan out over Gouda slices on a board with crackers.", "Pheasant breasts are small — watch closely, they dry out fast."),
    ("Small Game", "Pheasant Fried Rice", "Diced pheasant with rice, vegetables, and a fried egg on top.", "2 cups cooked pheasant (diced), 4 cups day-old rice, 2 eggs, 1 cup frozen peas, 3 tbsp soy sauce, 1 tbsp sesame oil, green onions, garlic", "Heat wok until smoking, scramble eggs and set aside. Add oil, fry pheasant until slightly crispy. Add rice and peas, soy sauce, sesame oil. Toss well, return eggs, top with green onions.", "Day-old rice is essential — fresh rice clumps and gets mushy."),
    ("Small Game", "Roasted Pheasant with Bacon and Thyme", "Whole pheasant wrapped in bacon and roasted with fresh thyme until golden.", "1 whole pheasant, 6 strips bacon, 4 sprigs thyme, 2 tbsp butter, 1 lemon, salt, pepper", "Season pheasant inside and out with salt, pepper, and thyme. Lay bacon across the breast, stuff cavity with lemon and remaining thyme. Roast at 400°F for 35-40 min until internal breast hits 150°F.", "The bacon bastes the pheasant as it renders — no basting needed."),
    ("Small Game", "Grouse Piccata with Capers and Lemon", "Pan-roasted grouse in a bright lemon-caper pan sauce.", "4 grouse breasts, 2 tbsp butter, 1/4 cup white wine, 1/4 cup chicken broth, 2 tbsp capers, 2 lemons, flour, salt, pepper", "Dredge grouse breasts in flour, salt, pepper. Brown in butter in a hot pan 3 min per side. Remove. Add wine, broth, capers, and lemon juice to pan — reduce by half. Return grouse, baste with sauce, serve.", "Grouse is tiny — portion one breast per person as an appetizer."),
    # FISH
    ("Fish", "Walleye Fish Tacos with Chipotle Cream", "Crispy walleye strips in corn tortillas with smoky chipotle cream and slaw.", "1 lb walleye fillets, 1/2 cup mayo, 2 chipotles in adobo, 1 cup shredded cabbage, corn tortillas, lime, salt, flour, oil", "Season and flour walleye, fry at 375°F until golden. Mix mayo with minced chipotles and lime. Warm tortillas, layer fish, cabbage, chipotle cream. Finish with lime.", "Walleye is mild — the chipotle cream gives it personality."),
    ("Fish", "Campfire Cedar Plank Salmon", "Salmon slow-roasted on a cedar plank over the campfire. Infinitely smoky.", "2 lb salmon fillet, 2 tbsp olive oil, 1 lemon, 4 sprigs dill, 2 cloves garlic, salt, pepper", "Soak cedar plank 1 hour. Oil plank, lay salmon skin-side down. Top with lemon slices, dill, garlic. Place near (not in) hot coals for 45-60 min until fish flakes easily. Don't flip.", "Keep the fire hot and the plank away from direct flame — you want smoking heat, not cooking heat."),
    ("Fish", "Pan-Fried Trout with Brown Butter and Almonds", "Crispy-skinned trout with nutty brown butter and toasted almonds.", "4 trout fillets, 4 tbsp butter, 1/4 cup sliced almonds, 1 lemon, 2 tbsp fresh parsley, salt, pepper", "Season trout with salt and pepper. Sear skin-side down in a hot cast iron 3-4 min until crispy. Flip, cook 1 more min. Add butter and almonds to pan, cook until butter browns and almonds toast. Pour over fish with parsley and lemon.", "Trout skin is delicate — let it get crispy before you try to flip."),
    ("Fish", "Smoked Steelhead Trout Dip", "Creamy smoked trout dip with cream cheese, lemon, and fresh dill.", "8 oz smoked steelhead trout, 8 oz cream cheese, 1/4 cup sour cream, 2 tbsp lemon juice, 2 tbsp fresh dill, 1 tbsp horseradish, salt, pepper", "Flake trout into a bowl. Soften cream cheese, mix with sour cream, lemon, dill, horseradish. Fold in trout. Season and chill 1 hour. Serve with crackers.", "Make it ahead — the flavors meld and improve overnight."),
    ("Fish", "Walleye Au Gratin", "Walleye fillets baked under a golden cracker crust with cheese and cream.", "1.5 lbs walleye fillets, 1 cup crushed saltines, 1 cup shredded cheddar, 1 cup heavy cream, 3 tbsp butter, 1 shallot, salt, pepper, paprika", "Place walleye in a buttered baking dish. Top with cream and minced shallot. Cover with crushed crackers and cheddar, dot with butter. Bake 375°F for 25 min until golden and bubbling.", "Heavy cream makes this luxuriously rich — a little goes a long way."),
    ("Fish", "Perch Meunière with Parsley and Lemon", "Classic French preparation: golden fried perch with brown butter, parsley, and lemon.", "1 lb perch fillets, 4 tbsp butter, 2 tbsp fresh parsley, 2 lemons, flour, salt, pepper", "Dredge perch in flour with salt and pepper. Fry in butter in a cast iron until golden 2-3 min per side. Add more butter to the pan, cook until nutty brown. Pour over fish, squeeze lemon, scatter parsley.", "Meunière is one of the simplest and best preparations for mild white fish."),
    ("Fish", "Muskie Fish Cakes with Cajun Remoulade", "Pan-fried muskellunge cakes with a spicy Cajun dipping sauce.", "1 lb muskellunge fillet (or pike), 2 eggs, 1/2 cup breadcrumbs, 2 tbsp Cajun seasoning, 1/2 cup mayo, 2 tbsp mustard, 1 tbsp horseradish, 1 tbsp pickle relish, lemon", "Poach fish, cool and flake. Mix with eggs, breadcrumbs, and seasoning. Form into patties, pan-fry in oil until golden. Mix remoulade: mayo, mustard, horseradish, relish. Serve fish cakes with remoulade.", "Muskie is firm and mild — holds together well as a cake."),
    ("Fish", "Carp with Lemon-Dill Beurre Blanc", "Pan-roasted carp with a silky butter sauce. A French bistro classic.", "1.5 lb carp fillet, 6 tbsp butter, 2 tbsp fresh dill, 2 shallots, 1/4 cup white wine, 1/4 cup heavy cream, lemon, salt, pepper", "Season and sear carp skin-side down in 2 tbsp butter until crispy. Flip, cook through. Remove. Add shallots, wine, cream to pan — reduce by half. Whisk in remaining butter off heat, add dill and lemon. Spoon over carp.", "Beurre blanc is fragile — don't let it boil after you add the butter."),
    ("Fish", "Catfish Po' Boy with Remoulade", "Crispy catfish on a baguette with creamy remoulade and pickled vegetables.", "1 lb catfish fillets, 1 cup cornmeal, 1 tbsp Cajun seasoning, 1 baguette, 1/2 cup mayo, 2 tbsp Creole mustard, 1 tbsp pickle relish, shredded lettuce, tomato", "Season catfish with Cajun spice, dredge in cornmeal, fry until golden. Mix mayo, mustard, relish for remoulade. Toast baguette, spread remoulade, pile on catfish, top with lettuce and tomato.", "Catfish is mild and absorbs the spice beautifully — don't skip the remoulade."),
    ("Fish", "Sturgeon Kedgeree", "Smoked sturgeon flaked into curried rice with hard-boiled eggs. British colonial comfort.", "1 lb smoked sturgeon (or salmon), 3 cups cooked rice, 4 eggs, 1 onion, 1 tsp curry powder, 1/4 cup cream, butter, lemon, parsley", "Hard-boil eggs, set aside. Sauté onion in butter, add curry powder, cook 1 min. Add rice and cream, heat through. Flake in sturgeon, fold in eggs, season, add lemon and parsley.", "Smoked sturgeon is worth seeking out — the firm flesh is extraordinary."),
    # CAMPFIRE
    ("Campfire", "Dutch Oven Campfire Chili — 5 Hours, Worth the Wait", "Five hours over coals transforms elk shoulder into fall-apart tender chili.", "2 lbs elk shoulder, 2 cans kidney beans, 1 can diced tomatoes, 1 onion, 4 cloves garlic, 3 tbsp chili powder, 1 tbsp cumin, salt, charcoal coals", "Cut elk into large chunks, brown in Dutch oven over fire. Add everything else, stir. Cover and pile 15-20 hot coals under the oven, 10-12 on top. Cook 5 hours, checking every hour. The meat will melt.", "Use a chimney starter to get coals ready — you want steady, even heat."),
    ("Campfire", "Campfire Flatbread with Wild Boar Sausage", "Cast iron-grilled flatbread topped with sliced and charred wild boar sausage.", "2 cups flour, 1 cup warm water, 1 tsp salt, 1 tsp yeast, 1 lb wild boar sausage, 1 onion, mustard, cheese (optional)", "Mix flour, water, salt, yeast — let rise 1 hour. Roll thin, grill on a cast iron over medium coals 2 min per side. Brown sausage in the same pan, char onion. Top flatbread with mustard, sausage, onion.", "The dough is simple — no rising time needed if you're in a hurry."),
    ("Campfire", "Campfire Breakfast Burritos", "Eggs,elk sausage, potatoes, and cheese wrapped in a grilled tortilla.", "6 eggs, 1 lb elk breakfast sausage, 2 cups hash browns, 6 flour tortillas, 1 cup shredded cheese, salsa verde, butter", "Brown elk sausage in cast iron, set aside. Cook potatoes in butter until crispy. Scramble eggs in the same pan. Warm tortillas, fill with everything, fold and roll. Char the outside on the griddle.", "Make ahead and wrap in foil — they reheat over the fire beautifully."),
    ("Campfire", "Campfire Shrimp Boil", "Old Bay-seasoned shrimp, sausage, and corn boiled in one pot over the fire.", "2 lbs shrimp (shell-on), 1 lb andouille sausage, 4 ears corn (cut in thirds), 1/4 cup Old Bay seasoning, 4 cloves garlic, lemon", "Boil a large pot of salted water with Old Bay and garlic. Add corn and sausage, cook 10 min. Add shrimp, cook 2-3 min until pink. Drain, squeeze lemon over, serve with melted butter.", "Don't overcook the shrimp — they continue to cook after you drain them."),
    ("Campfire", "Ember-Roasted Acorn Squash with Sage Butter", "Whole acorn squash roasted in embers until caramelized, topped with nutty sage butter.", "2 acorn squash, 4 tbsp butter, 8 fresh sage leaves, 2 tbsp maple syrup, salt, pepper", "Cut squash in half, remove seeds. Place cut-side down directly on embers or in a Dutch oven. Cook 45 min until soft. Meanwhile, cook sage in butter until crispy. Flip squash, fill with sage butter and maple syrup.", "The embers caramelize the sugars — this is a campfire classic for a reason."),
    ("Campfire", "Ember-Roasted Whole Duck", "A whole duck roasted in the embers of a campfire until the skin is crackling and the meat is tender.", "1 whole duck (4-5 lbs), 2 tbsp coarse salt, 1 orange (quartered), 6 sprigs thyme", "Rub the duck all over with salt, inside and out. Stuff with orange and thyme. Bury in hot embers, cook 2-3 hours, turning every 30 min. The skin should be crackling and mahogany.", "Protect the duck from direct flame with a grate or heavy pan — you're smoking it, not charring it."),
    ("Campfire", "Dutch Oven Sourdough Bread", "Rustic sourdough baked in a Dutch oven over the campfire. Crusty, tangy, incredible.", "2 cups sourdough starter, 4 cups flour, 1.5 tsp salt, 1 cup warm water", "Mix starter, flour, salt, and water into a shaggy dough. Let rise 4-6 hours. Shape into a round, let rest 30 min. Score the top. Place in a greased Dutch oven, cover, cook 30 min with coals on top and bottom. Uncover, cook 15 more min until deep golden.", "A sourdough starter is required — maintain one before your trip."),
    ("Campfire", "Dutch Oven Cinnamon Rolls", "Gooey cinnamon rolls with cream cheese frosting baked in a Dutch oven.", "2 tubes refrigerator biscuits, 4 tbsp butter, 1/2 cup brown sugar, 2 tbsp cinnamon, 4 oz cream cheese, 1/4 cup powdered sugar, 2 tbsp milk", "Melt butter in Dutch oven. Mix brown sugar and cinnamon. Separate biscuits, dip in butter, coat with sugar mixture. Arrange in pot. Cook over medium coals 15 min until golden. Mix cream cheese, powdered sugar, milk — frost warm rolls.", "Refrigerator biscuits are the camp-friendly shortcut — nobody needs to know."),
    # DUTCH OVEN
    ("Dutch Oven", "Dutch Oven Beef Stew", "Classic beef stew with root vegetables, browned meat, and rich gravy.", "2 lbs elk or bison shoulder, 4 potatoes, 3 carrots, 2 parsnips, 1 onion, 4 cups beef broth, tomato paste, thyme, bay leaf, flour, salt, pepper", "Cut meat into chunks, brown in batches in Dutch oven. Add onion, cook 5 min. Dust with flour, stir. Add broth, tomato paste, herbs. Bring to simmer, cover and cook 1 hour. Add vegetables, cook 45 more min.", "A cast iron Dutch oven over coals is the best stew pot ever invented."),
    ("Dutch Oven", "Dutch Oven Cornbread", "Golden,crumbly cornbread baked in a Dutch oven with crispy edges.", "1.5 cups cornmeal, 1.5 cups flour, 1/4 cup sugar, 1 tbsp baking powder, 1 tsp salt, 2 eggs, 1.5 cups milk, 1/3 cup oil or melted butter", "Mix dry ingredients. Whisk eggs, milk, and oil. Combine, pour into hot greased Dutch oven. Bake with 12 coals on bottom, 8 on top for 25-30 min until golden and a toothpick comes out clean.", "A hot Dutch oven is the secret to a crispy bottom crust."),
    ("Dutch Oven", "Dutch Oven Pot Roast with Red Wine and Rosemary", "Elk or bison pot roast braised in red wine until fork-tender.", "3 lb elk or bison roast, 1 bottle red wine, 4 potatoes, 4 carrots, 1 onion, 4 cloves garlic, 3 sprigs rosemary, 2 tbsp butter, salt, pepper", "Season and sear roast. Add sliced onion and garlic, cook 5 min. Pour in wine, add rosemary. Cover and cook over low coals 3 hours. Add potatoes and carrots in last hour.", "This works with any big-game roast — elk, bison, deer all benefit from the long braise."),
    ("Dutch Oven", "Dutch Oven Apple Cinnamon Cobbler", "Warm spiced apples under a golden biscuit topping. Camp comfort food.", "6 Granny Smith apples, 1/2 cup sugar, 2 tsp cinnamon, 2 cups biscuit mix, 1 cup milk, 4 tbsp butter, nutmeg", "Slice apples, toss with sugar and cinnamon. Melt butter in Dutch oven, add apples. Mix biscuit mix and milk, pour over apples. Cover and cook over medium coals 25 min until topping is golden.", "Serve warm with whipped cream or vanilla ice cream if you have it."),
    # SMOKER/BBQ
    ("Smoker", "Smoked Elk Summer Sausage", "Coarsely ground elk with pork fat and spices, slow-smoked until deeply set.", "2 lbs elk, 1/2 lb pork fat, 2 tbsp mustard seed, 1 tbsp coriander, 1 tbsp black pepper, 1 tsp garlic powder, 1 tsp Prague powder #1, salt", "Grind elk and pork fat through coarse plate. Mix in seasonings and Prague powder. Stuff into hog casings. Smoke at 160°F 4 hours, then 180°F until internal reaches 155°F. Slice thin and serve at room temperature.", "Elk summer sausage is a project — but it keeps for weeks in the cooler."),
    ("Smoker", "Smoked Elk Leg Roast", "Brined elk leg roasted and smoked until medium-rare with a juniper and oak smoke flavor.", "1 elk leg roast (boneless), 1/4 cup salt, 1/4 cup brown sugar, 2 tbsp juniper berries, 4 sprigs rosemary, oak wood chips", "Brine elk leg in salt, sugar, and crushed juniper berries for 24 hours. Smoke at 225°F for 3-4 hours until internal hits 130°F for medium-rare. Rest 20 min, slice thin against the grain.", "Brining keeps the lean elk moist — don't skip this step."),
    ("Smoker", "Smoked Duck Breast with Maple and Black Pepper", "Cured and cold-smoked duck breast with a maple-peppercorn glaze.", "4 duck breasts, 2 tbsp maple syrup, 1 tbsp coarse black pepper, 1 tbsp salt, 2 cups wood chips (apple or cherry)", "Cure duck breasts with salt 4 hours or overnight. Rinse, pat dry, cold-smoke 2 hours. Brush with maple syrup mixed with pepper, smoke 30 more min. Slice thin and serve.", "Cold-smoking adds flavor without cooking — the duck is raw but cured and safe."),
    ("Smoker", "Smoked Pheasant with Sage and Apple", "Whole pheasant smoked with fresh sage and apple wood until tender.", "2 whole pheasants, 6 sprigs sage, 1 apple (quartered), 2 tbsp butter, salt, pepper, apple wood chips", "Season pheasants inside and out with salt, pepper, and sage. Place apple quarters inside. Smoke at 225°F for 2 hours, basting with butter halfway. Rest 15 min before carving.", "Pheasant is lean — the smoke and apple keep it from drying out."),
    ("Smoker", "Smoked Wild Mushrooms", "Forest mushrooms slow-smoked with hickory until deeply savory and chewy.", "2 lbs mixed mushrooms (shiitake, oyster, cremini), 3 tbsp olive oil, 2 tbsp soy sauce, 1 tbsp balsamic vinegar, 2 cloves garlic, salt", "Clean mushrooms, toss with oil, soy sauce, vinegar, garlic, and salt. Smoke at 180°F for 2-3 hours until leathery and dark. They're intensely savory — a little goes a long way.", "Serve as a side, crumble into soups, or chop into scrambled eggs."),
    # SIDES
    ("Sides", "Cast Iron Campfire Beans", "Smoky baked beans with bacon and molasses, cooked in a cast iron over the fire.", "2 cans kidney beans, 6 strips bacon, 1/2 cup molasses, 2 tbsp Dijon mustard, 1 onion, 2 cloves garlic, salt", "Cook bacon in cast iron until crispy, set aside. Sauté onion and garlic in bacon fat. Add beans, molasses, mustard, crumble in bacon. Simmer over fire 30 min until thick and glossy.", "These beans get better the longer they sit — make them first and let them go."),
    ("Sides", "Cast Iron Campfire Cornbread with Honey Butter", "Golden cornbread with a crispy bacon-chili crust and honey butter.", "1.5 cups cornmeal, 1 cup flour, 1 tbsp baking powder, 1 tsp salt, 1 egg, 1 cup milk, 1/3 cup oil, 4 tbsp butter, 1/4 cup honey", "Mix dry, whisk in egg, milk, and oil. Melt 2 tbsp butter in hot cast iron, pour in batter. Cook over medium coals 15 min, flip and cook 10 more min. Mix remaining butter with honey for serving.", "The bacon drippings in the pan make the crust — don't substitute vegetable oil."),
    ("Sides", "Smoked Wild Mushrooms", "Forest mushrooms slow-smoked with hickory until deeply savory.", "2 lbs mixed mushrooms, 3 tbsp olive oil, 2 tbsp soy sauce, 1 tbsp balsamic vinegar, 2 cloves garlic, hickory chips, salt", "Clean and halve mushrooms. Toss with oil, soy sauce, vinegar, garlic, and salt. Smoke at 180°F for 2 hours until leathery and dark brown. Serve warm or cold as a side dish.", "Smoked mushrooms are umami bombs — chop and add to pasta, risotto, or eggs."),
    ("Sides", "Campfire Grilled Street Corn", "Charred corn on the cob with mayo, cotija, chili, and lime.", "6 ears corn (in husk), 1/2 cup mayo, 1 cup cotija cheese (or feta), 2 tsp chili powder, 2 limes, cilantro, salt", "Pull back husks, grill directly over hot coals until charred on all sides. Roll in mayo, sprinkle with cheese, chili powder, squeeze lime over top, scatter cilantro.", "Cotija is a crumbly Mexican cheese — feta is the closest substitute."),
    ("Sides", "Dutch Oven Sourdough Bread", "Crusty rustic sourdough baked in a Dutch oven over coals.", "2 cups sourdough starter, 4 cups flour, 1.5 tsp salt, 1 cup warm water", "Mix into shaggy dough, let rise 4-6 hours. Shape into round, score top. Place in hot greased Dutch oven, cover. Stack 12 coals on bottom, 8 on top. Cook 30 min covered, 15 min uncovered until deep brown.", "Requires a maintained sourdough starter — worth the effort for fresh camp bread."),
]

def slugify(title):
    return title.lower().replace(" — ", "-").replace(" ", "-").replace(",", "").replace("'", "").replace("!", "").replace(":", "").replace(".", "")

def make_image_choices():
    # Pick from base images
    choices = random.choice(BASE_IMAGES)
    return choices

def generate_page(tag, title, description, ingredients, instructions, tips, filename, image):
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} — Tag Soup</title>
  <meta name="description" content="{description}">
  <meta property="og:title" content="{title}">
  <meta property="og:type" content="article">
  <meta property="og:image" content="https://kodaagentmt-max.github.io/tag-soup-blog/images/{image}">
  <meta property="og:url" content="https://kodaagentmt-max.github.io/tag-soup-blog/posts/{filename}.html">
  <style>
    body {{ background: #1a0f00; color: #f0e0c0; font-family: Georgia, serif; margin: 0; padding: 40px 20px; }}
    .container {{ max-width: 720px; margin: 0 auto; }}
    .tag {{ font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #e87820; margin-bottom: 10px; }}
    h1 {{ font-size: 28px; color: #f5c518; margin-bottom: 12px; line-height: 1.3; }}
    .meta {{ font-size: 12px; color: #c4a97a; margin-bottom: 24px; }}
    .hero-img {{ width: 100%; max-height: 400px; object-fit: cover; border-radius: 8px; margin-bottom: 28px; display: block; }}
    .body {{ font-size: 17px; line-height: 1.9; margin-bottom: 24px; }}
    .section {{ background: #2a1a00; border-left: 3px solid #e87820; padding: 14px 18px; margin: 24px 0; font-size: 15px; }}
    .section h3 {{ color: #e87820; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; }}
    .back {{ color: #e87820; text-decoration: none; font-size: 13px; }}
    .brand-banner {{ background: #e87820; padding: 10px 20px; text-align: center; }}
    .brand-banner a {{ color: #fff; text-decoration: none; font-size: 13px; font-weight: 600; font-family: Inter, sans-serif; letter-spacing: 0.5px; }}
    .brand-banner a:hover {{ color: #f5c518; }}
    .photo-credit {{ font-size: 11px; color: #c4a97a; text-align: right; margin-bottom: 24px; }}
  </style>
</head>
<body>
  <div class="brand-banner"><a href="/tag-soup-blog/">← Back to Tag Soup — Camp Cook Kitchen</a></div>
  <div class="container">
    <img class="hero-img" src="../images/{image}" alt="{title}">
    <div class="tag">{tag}</div>
    <h1>{title}</h1>
    <div class="meta">🔥 Camp Cook Kitchen — Tag Soup</div>
    <p class="body">{description}</p>
    <div class="section">
      <h3>🫏 What You'll Need</h3>
      <p>{ingredients}</p>
    </div>
    <p class="body">{instructions}</p>
    <div class="section">
      <h3>💡 Pro Tips</h3>
      <p>{tips}</p>
    </div>
    <p class="photo-credit">🔥 Tag Soup — Wild Game & Outdoor Cooking</p>
    <a class="back" href="/tag-soup-blog/">← Back to Tag Soup</a>
  </div>
</body>
</html>'''
    return html

# Generate all pages
posts_data = []
for i, recipe in enumerate(RECIPES):
    tag, title, description, ingredients, instructions, tips = recipe
    slug = slugify(title)
    image = random.choice(BASE_IMAGES)
    filename = f"{slug}.html"
    html = generate_page(tag, title, description, ingredients, instructions, tips, filename, image)
    filepath = POSTS_DIR / filename
    filepath.write_text(html)
    posts_data.append({
        "id": f"recipe-{i+1:03d}",
        "title": title,
        "filename": filename,
        "tag": tag
    })
    if (i+1) % 20 == 0:
        print(f"  Generated {i+1}/{len(RECIPES)} pages...")

print(f"Done! Generated {len(posts_data)} recipe pages.")
print(f"Files: {len(list(POSTS_DIR.glob('*.html')))} HTML files in {POSTS_DIR}")

# Save posts.json
(BLOG_DIR / "posts.json").write_text(json.dumps(posts_data, indent=2))
print(f"posts.json updated with {len(posts_data)} recipes.")
